// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgxPY7Zzac56_6R-5wnNJT9AsmnYXY-xg',
    appId: '1:1079702034755:web:fc62ae9c9f6dd2a19d37f6',
    messagingSenderId: '1079702034755',
    projectId: 'layop-d6202',
    authDomain: 'layop-d6202.firebaseapp.com',
    storageBucket: 'layop-d6202.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkdztrQyeQ0QSI9NLEWFfSIX4oG9VHz08',
    appId: '1:1079702034755:android:7c4304cbe0343a9c9d37f6',
    messagingSenderId: '1079702034755',
    projectId: 'layop-d6202',
    storageBucket: 'layop-d6202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mFmF0cUxF40IBCBbZZcOfC3FW5H01mA',
    appId: '1:1079702034755:ios:3dbf106ca82bde5d9d37f6',
    messagingSenderId: '1079702034755',
    projectId: 'layop-d6202',
    storageBucket: 'layop-d6202.appspot.com',
    iosClientId: '1079702034755-pugu6b7esp9599dbge84n288eb9jrqm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.layop2',
  );
}
